import { ArrowRight, BookOpenCheck, CheckCircle2, Code2, Database, FlaskConical } from 'lucide-react'
import { AppHeader, type AppSection } from '../components/AppHeader'
import { getProblemProgress } from '../services/storage'
import type { ActivityMap, LearningChapter, MatplotlibQuestion, PandasQuestion, ProgressMap, ProjectProgressMap, SqlProblem } from '../types/problem'

interface Props {
  problems: SqlProblem[]; pandasProblems: PandasQuestion[]; matplotlibProblems: MatplotlibQuestion[]; chapters: LearningChapter[]; progress: ProgressMap; activity: ActivityMap; completedLessons: string[]; projectProgress: ProjectProgressMap
  onOpen: (id: string) => void; onOpenPandas: (id: string) => void; onOpenMatplotlib: (id: string) => void; onReset: () => void; onNavigateSection: (section: AppSection) => void
}

export function DashboardPage({ problems, pandasProblems, matplotlibProblems, progress, completedLessons, onOpen, onOpenPandas, onOpenMatplotlib, onReset, onNavigateSection }: Props) {
  const sqlDone = problems.filter((item) => getProblemProgress(progress, item.id).completed).length
  const pandasDone = pandasProblems.filter((item) => getProblemProgress(progress, item.id).completed).length
  const matplotlibDone = matplotlibProblems.filter((item) => getProblemProgress(progress, item.id).completed).length
  const recent = [...problems, ...pandasProblems, ...matplotlibProblems].filter((item) => getProblemProgress(progress, item.id).attempts > 0).sort((a, b) => (getProblemProgress(progress, b.id).lastAttemptAt ?? '').localeCompare(getProblemProgress(progress, a.id).lastAttemptAt ?? '')).slice(0, 3)
  const next = problems.find((item) => !getProblemProgress(progress, item.id).completed) ?? problems[0]
  const reset = () => { if (window.confirm('确定重置全部学习记录、错题与草稿吗？')) onReset() }

  return <div className="home-page atlas-page"><AppHeader completed={sqlDone + pandasDone + matplotlibDone} total={problems.length + pandasProblems.length + matplotlibProblems.length} currentSection="dashboard" onHome={() => onNavigateSection('dashboard')} onNavigateSection={onNavigateSection} onReset={reset} /><main className="home-main atlas-main dashboard-compact">
    <section className="compact-hero"><div><span className="eyebrow">SQL + PANDAS LEARNING LAB</span><h1>把数据分析能力，<br />练成可交付的工作方法。</h1><p>按清晰路线学习概念，用真实小表练习，再用另一种语言验证同一条数据转换。</p><div className="hero-actions"><button className="primary-button" onClick={() => onNavigateSection(completedLessons.length ? 'learn' : 'learn')}>{completedLessons.length ? '继续学习' : '开始学习'}<ArrowRight size={17} /></button><button className="secondary-button" onClick={() => onOpen(next.id)}>开始练习</button><button className="text-link" onClick={() => onNavigateSection('compare')}>查看双语对照</button></div></div><div className="hero-flow" aria-label="学习流程"><span><Database size={19} />原始数据</span><ArrowRight size={18} /><span><Code2 size={19} />分析转换</span><ArrowRight size={18} /><span><CheckCircle2 size={19} />图表与结论</span></div></section>
    <section className="quick-entry-grid" aria-label="快捷入口"><Quick icon={<BookOpenCheck />} title="学习地图" text="10 个 SQL 模块、10 个 Pandas 模块与可视化短课" action="继续课程" onClick={() => onNavigateSection('learn')} /><Quick icon={<Database />} title="练习中心" text={`${problems.length + pandasProblems.length + matplotlibProblems.length} 道分层练习，保留筛选进度`} action="开始练习" onClick={() => onNavigateSection('practice')} /><Quick icon={<FlaskConical />} title="自由实验" text="在小数据集上即时查看转换结果" action="打开实验台" onClick={() => onNavigateSection('playground')} /></section>
    <section className="dual-progress-section"><div className="section-heading"><div><span className="eyebrow">DUAL TRACK</span><h2>双轨进度</h2></div><button className="text-link" onClick={() => onNavigateSection('report')}>完整学习报告 <ArrowRight size={15} /></button></div><div className="dual-progress-grid"><Progress title="SQL" done={sqlDone} total={problems.length} /><Progress title="Pandas" done={pandasDone} total={pandasProblems.length} supplement={`可视化交付 ${matplotlibDone}/${matplotlibProblems.length}`} /></div></section>
    <section className="stage-map"><div className="section-heading"><div><span className="eyebrow">FOUR STAGES</span><h2>从基础查询到完整分析</h2></div></div><div>{[['01','取数基础','筛选、排序、表达式'],['02','分析核心','聚合、连接、日期'],['03','进阶转换','窗口、CTE、清洗'],['04','项目交付','指标、验证、结论']].map(([n,t,d]) => <article key={n}><span>{n}</span><strong>{t}</strong><small>{d}</small></article>)}</div></section>
    {recent.length > 0 && <section className="compact-recent"><div className="section-heading"><div><span className="eyebrow">RECENT</span><h2>继续上次练习</h2></div></div><div>{recent.map((item) => <button key={item.id} onClick={() => item.language === 'matplotlib' ? onOpenMatplotlib(item.id) : item.language === 'pandas' ? onOpenPandas(item.id) : onOpen(item.id)}><span className={`language-badge ${item.language ?? 'sql'}`}>{item.language === 'matplotlib' ? 'Matplotlib' : item.language === 'pandas' ? 'Pandas' : 'SQL'}</span><strong>{item.title}</strong><small>{getProblemProgress(progress, item.id).completed ? '已完成' : '继续练习'}</small><ArrowRight size={16} /></button>)}</div></section>}
  </main></div>
}

function Quick({ icon, title, text, action, onClick }: { icon: React.ReactNode; title: string; text: string; action: string; onClick: () => void }) { return <button className="quick-entry-card" onClick={onClick}><i>{icon}</i><strong>{title}</strong><span>{text}</span><b>{action}<ArrowRight size={15} /></b></button> }
function Progress({ title, done, total, supplement }: { title: string; done: number; total: number; supplement?: string }) { const percent = total ? Math.round(done / total * 100) : 0; return <article className="compact-progress-card"><div><strong>{title}</strong><span>{done} / {total} 题</span><b>{percent}%</b></div><i><span style={{ width: `${percent}%` }} /></i>{supplement&&<small className="progress-supplement">{supplement}</small>}</article> }
